# Properties de este proceso
QUERY_DIRECTA : SELECT * FROM Person
QUERY_PARAM : SELECT * FROM Person WHERE id = ?

PROCEDURE_OBTENER_PERSONAS : list_person
PROCEDURE_OBTENER_PERSONA_ID : list_person_id

